### ISSUE TITLE
Unable to build, missing winstrct.props

### ISSUE THREAD

**Issue by voltagex** [LTRData/rawcopy#1]
```
PS C:\git\rawcopy> msbuild
MSBuild version 17.5.1+f6fdcf537 for .NET Framework
Building the projects in this solution one at a time. To enable parallel build, please add the "-m" switch.
Build started 21/05/2023 2:32:08 PM.
Included response file: C:\Program Files (x86)\Microsoft Visual Studio\2022\BuildTools\MSBuild\Current\Bin\amd64\MSBuild.rsp

Project "C:\git\rawcopy\rawcopy.sln" on node 1 (default targets).
ValidateSolutionConfiguration:
  Building solution configuration "Debug|Win32".
Project "C:\git\rawcopy\rawcopy.sln" (1) is building "C:\git\rawcopy\rawcopy.vcxproj" (2) on node 1 (default targets).
C:\git\rawcopy\rawcopy.vcxproj(57,5): error MSB4019: The imported project "C:\git\winstrct.props" was not found. Confirm that the expression in the Import declaration "..\winstrct.props" is correct, and that the file exists on disk.
Done Building Project "C:\git\rawcopy\rawcopy.vcxproj" (default targets) -- FAILED.

Done Building Project "C:\git\rawcopy\rawcopy.sln" (default targets) -- FAILED.


Build FAILED.

"C:\git\rawcopy\rawcopy.sln" (default target) (1) ->
"C:\git\rawcopy\rawcopy.vcxproj" (default target) (2) ->
  C:\git\rawcopy\rawcopy.vcxproj(57,5): error MSB4019: The imported project "C:\git\winstrct.props" was not found. Confirm that the expression in the Import declaration "..\winstrct.props" is correct, and that the file exists on disk.
```

Could you please provide this file?

Thanks for ImDisk and all these useful utilities.

**Comment by voltagex** [comment]
Actually it seems like a lot of other stuff is missing too.

**Comment by Olof-Lagerkvist** [comment]
You need header files from this repo:
https://github.com/LTRData/include

**Comment by Olof-Lagerkvist** [comment]
But props files still seem missing. I'll take a look at what has happened here.

**Comment by Olof-Lagerkvist** [comment]
I created a separate repo for the props files now. If there are any missing now they are just related to my own signing certificates and similar, so you could safely remove them from the project (property sheets tab). Also modified rawcopy project file to search for props files in `..\props` directory and in turn the props files to search for header files in `..\include`, so if you clone props and include repos to these paths I think it should work.

**Comment by DavidSayada** [comment]
Hi, can you please indicate where is the repo for the props file? Thank you in advance.

**Comment by Olof-Lagerkvist** [comment]
> Hi, can you please indicate where is the repo for the props file? Thank you in advance.

https://github.com/LTRData/props

**Comment by DavidSayada** [comment]
Hi, it seems this repo is not accessible, I am getting a 404 error, thank you for posting anyway.

**Comment by Olof-Lagerkvist** [comment]
> Hi, it seems this repo is not accessible, I am getting a 404 error, thank you for posting anyway.

You are right, I had missed that! Should be public now!

**Comment by DavidSayada** [comment]
Sounds good, thank you, have a nice day.

**Comment by DavidSayada** [comment]
Hi,

Still very hard to compile the project with Visual Studio 2022, and I don't have Visual Studio 2013.
You may want to perform the requested changes in order to have the project compiled with latest Visual Studio releases?

Thanks in advance!

**Comment by Olof-Lagerkvist** [comment]
> Hi,
> 
> Still very hard to compile the project with Visual Studio 2022, and I don't have Visual Studio 2013. You may want to perform the requested changes in order to have the project compiled with latest Visual Studio releases?

I have not tried to build it in "modern" Visual Studio versions, but I can imagine there are some challenges with that. I have a kind of long-term project of keeping the code bases compatible with old toolchains for command line builds, while upgrading Visual Studio project files to be compatible with later versions. But it means quite some work and it will take some time, unfortunately.

The code itself is compatible with latest VS versions though. For example, I build the ARM64 versions using command line scripts and VS 2017 toolchains.

**Comment by DavidSayada** [comment]
Hi, almost done, can you please indicate where to find the winstrcp.lib library? Compilation seems OK, I now have link errors.

**Comment by Olof-Lagerkvist** [comment]
I published the lib source files as a separate repo now to make things a bit easier. There is really no reason to build an intermediate lib file when building from Visual Studio.
https://github.com/LTRData/libsrc
I also pushed some minor changes to https://github.com/LTRData/include and https://github.com/LTRData/rawcopy to make it all build together. Seems to work now as far as I can see.

**Comment by DavidSayada** [comment]
Thank you so much, I will update you with my results.

**Comment by DavidSayada** [comment]
I now get the following error when opening the solution with Visual Studio 2013, with the previous commit I could at least compile>

`C:\Test\rawcopy\rawcopy.vcxproj : error  : Unable to read the project file "rawcopy.vcxproj".
C:\Program Files (x86)\MSBuild\12.0\bin\Microsoft.Common.CurrentVersion.targets(94,27): A numeric comparison was attempted on "$(TargetPlatformVersion)" that evaluates to "10.0.19041.0" instead of a number, in condition "'$(UseOSWinMdReferences)' == '' and ('$(TargetPlatformWinMDLocation)' == '' and '$(TargetPlatformIdentifier)' == 'Windows' and '$(TargetPlatformVersion)' > '7.0')".
`

**Comment by Olof-Lagerkvist** [comment]
> I now get the following error when opening the solution with Visual Studio 2013, with the previous commit I could at least compile>
> 
> `C:\Test\rawcopy\rawcopy.vcxproj : error : Unable to read the project file "rawcopy.vcxproj". C:\Program Files (x86)\MSBuild\12.0\bin\Microsoft.Common.CurrentVersion.targets(94,27): A numeric comparison was attempted on "$(TargetPlatformVersion)" that evaluates to "10.0.19041.0" instead of a number, in condition "'$(UseOSWinMdReferences)' == '' and ('$(TargetPlatformWinMDLocation)' == '' and '$(TargetPlatformIdentifier)' == 'Windows' and '$(TargetPlatformVersion)' > '7.0')". `

It is no longer compatible with Visual Studio 2013. It needs 2017 or later.

**Comment by DavidSayada** [comment]
Is Visual Studio 2022 supported then? According to what I see, it is not.

**Comment by Olof-Lagerkvist** [comment]
> Is Visual Studio 2022 supported then? According to what I see, it is not.

Just tried to build in Visual Studio 2022 here now and it worked. What errors did you get?

**Comment by DavidSayada** [comment]
Nice to hear this is compiling, you may want to share a little "HowTo" which will explain the community the compilation procedure?
Thanks in advance!

**Comment by DavidSayada** [comment]
Hi, I downloaded a Windows11 Virtual Box image from Microsoft official site where Visual Studio 2022 is pre-installed, please see below the kind of errors I am getting when trying to compile the rawcopy utility.

`Rebuild started at 12:21 AM...
1>------ Rebuild All started: Project: rawcopy, Configuration: Debug Win32 ------
1>C:\Program Files\Microsoft Visual Studio\2022\Community\MSBuild\Microsoft\VC\v170\Microsoft.Cpp.WindowsSDK.targets(46,5): error MSB8036: The Windows SDK version 10.0.19041.0 was not found. Install the required version of Windows SDK or change the SDK version in the project property pages or by right-clicking the solution and selecting "Retarget solution".
1>Done building project "rawcopy.vcxproj" -- FAILED.
========== Rebuild All: 0 succeeded, 1 failed, 0 skipped ==========
========== Rebuild completed at 12:21 AM and took 00.577 seconds ==========
`

**Comment by DavidSayada** [comment]
I confirm, this is compiling now, thank you so much!

**Comment by DavidSayada** [comment]
Hi, another little issue I have been able to identify, it seems that because of that it is not possible to compile any Release configuration.

`  <ImportGroup Label="PropertySheets" Condition="'$(Configuration)|$(Platform)'=='Release|Win32'">
    <Import Project="..\props\winstrct.props" />
    <Import Project="C:\Users\olof.OLOFDOM\Source\signltr.props" />
    <Import Project="Properties.props" />
  </ImportGroup>
  <ImportGroup Condition="'$(Configuration)|$(Platform)'=='Release|x64'" Label="PropertySheets">
    <Import Project="..\props\winstrct.props" />
    <Import Project="C:\Users\olof.OLOFDOM\Source\signltr.props" />
    <Import Project="Properties.props" />
  </ImportGroup>
  <ImportGroup Condition="'$(Configuration)|$(Platform)'=='Release|ARM'" Label="PropertySheets">
    <Import Project="..\props\winstrct.props" />
    <Import Project="C:\Users\olof.OLOFDOM\Source\signltr.props" />
    <Import Project="Properties.props" />
  </ImportGroup>
  <ImportGroup Condition="'$(Configuration)|$(Platform)'=='Release|ARM64'" Label="PropertySheets">
    <Import Project="..\props\winstrct.props" />
    <Import Project="C:\Users\olof.OLOFDOM\Source\signltr.props" />
    <Import Project="Properties.props" />
  </ImportGroup>
`

**Comment by Olof-Lagerkvist** [comment]
> Hi, another little issue I have been able to identify, it seems that because of that it is not possible to compile any Release configuration.
> 
> ` <ImportGroup Label="PropertySheets" Condition="'$(Configuration)|$(Platform)'=='Release|Win32'"> <Import Project="..\props\winstrct.props" /> <Import Project="C:\Users\olof.OLOFDOM\Source\signltr.props" /> <Import Project="Properties.props" /> </ImportGroup> <ImportGroup Condition="'$(Configuration)|$(Platform)'=='Release|x64'" Label="PropertySheets"> <Import Project="..\props\winstrct.props" /> <Import Project="C:\Users\olof.OLOFDOM\Source\signltr.props" /> <Import Project="Properties.props" /> </ImportGroup> <ImportGroup Condition="'$(Configuration)|$(Platform)'=='Release|ARM'" Label="PropertySheets"> <Import Project="..\props\winstrct.props" /> <Import Project="C:\Users\olof.OLOFDOM\Source\signltr.props" /> <Import Project="Properties.props" /> </ImportGroup> <ImportGroup Condition="'$(Configuration)|$(Platform)'=='Release|ARM64'" Label="PropertySheets"> <Import Project="..\props\winstrct.props" /> <Import Project="C:\Users\olof.OLOFDOM\Source\signltr.props" /> <Import Project="Properties.props" /> </ImportGroup>`

Oh, that's right. Please remove the references to signltr.props from Property Sheets tab in the solution. It is present under all release configurations.

**Comment by DavidSayada** [comment]
Also, you may know how to cope with this error when you try to run rawcopy on a computer different from the one where you did the compilation?

![image](https://github.com/LTRData/rawcopy/assets/157275481/7ca6072f-febb-47c4-8e9e-01808cfea3d8)

**Comment by Olof-Lagerkvist** [comment]
Yes, debug builds do not work without VC++ debug runtime installed. There are redistributable files available in a subdirectory to VS. The debug libraries are not redistributable, however.

**Comment by Olof-Lagerkvist** [comment]
For running release builds, you need to install one of the VC++ runtimes on target machines:
https://learn.microsoft.com/en-us/cpp/windows/latest-supported-vc-redist

**Comment by DavidSayada** [comment]
Yes, now that I can compile the Release configurations (thanks to your suggested changes) and that I installed the latest VC++ runtimes, I can execute the executable on another machine, thank you!

**Comment by Olof-Lagerkvist** [comment]
I am glad to hear that it worked!
