### ISSUE TITLE
How to copy files while preserving compression attributes?

### ISSUE THREAD

**Issue by nil-ref** [LTRData/rawcopy#2]
First, I compressed the file using the following command:
`compact /c /s /a /i /exe:lzx "log.txt"`

Then, I used the following command to copy:
`rawcopy.exe log.txt 2.txt`

But the compression of file "2.txt" is lost.

**Comment by Olof-Lagerkvist** [comment]
Rawcopy does not copy any file attributes or any other metadata at all. It only copies raw file or device data.
